### ISSUE TITLE
Crash on camera enable

### ISSUE THREAD

**Issue by licaon-kter** [dakhnod/Meshenger#6]
Xperia 6.0.1
```
E AndroidRuntime: Process: d.d.meshenger, PID: 29465
E AndroidRuntime:        at d.d.meshenger.RTCCall.setVideoEnabled(RTCCall.java:223)
E AndroidRuntime:        at d.d.meshenger.CallActivity.switchVideoEnabled(CallActivity.java:187)
E AndroidRuntime:        at d.d.meshenger.CallActivity.lambda$onCreate$1$CallActivity(CallActivity.java:136)
E AndroidRuntime:        at d.d.meshenger.CallActivity$$Lambda$3.onClick(Unknown Source)
```

**Comment by dakhnod** [comment]
thanks for the help, is that the whole stacktrace?
normally, in such a case, the exception messager and such are printed.

**Comment by jasonhfuller** [comment]
I can confirm this on LG Nexus 5x and Samsung Galaxy s4

**Comment by iamvasuh** [comment]
This issue has been fixed now. Checkout the link https://github.com/meshenger-app/meshenger-android

**Comment by mwarning** [comment]
Hopefully fixed in 2.0.0 now.
